repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((vss_cli|script|tests)/.+)?[^/]+\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
        files: ^(vss_cli|script|tests)/.+\.py$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=tests/bandit.yaml
        files: ^(vss_cli|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
  - repo: https://github.com/prettier/prettier
    rev: 2.0.4
    hooks:
      - id: prettier
        stages: [manual]
exclude: '^docs/conf.py'
